"""Generate forwarding COM methods from the locally installed Windows headers."""
import pathlib,re,sys
header=pathlib.Path(sys.argv[1]).read_text()
out=['// Generated by generate_wrappers.py; forwarding signatures from dinput.h.']
for suffix in ['A','W']:
 for device in [True,False]:
  interface=('IDirectInputDevice8' if device else 'IDirectInput8')+suffix
  cls=('Keyboard' if device else 'Input')+suffix
  text=header.split('DECLARE_INTERFACE_('+interface+',',1)[1].split('};',1)[0]
  out.append(f'class {cls} final : public {interface} {{\npublic:\n {interface}* raw; LONG refs=1; bool format=false; LONG stateLogged=0,dataLogged=0; HybridKeyboard hybrid;\n explicit {cls}({interface}* p):raw(p){{}}\n ~{cls}(){{raw->Release();}}')
  if not device:
   out.append(f'''struct EnumContext {{ LPDIENUMDEVICESCALLBACK{suffix} callback; void* context; }};
static BOOL CALLBACK filter(const DIDEVICEINSTANCE{suffix}* d, void* p) {{
 auto c=(EnumContext*)p;DWORD t=GET_DIDEVICE_TYPE(d->dwDevType);
 if(t!=DI8DEVTYPE_KEYBOARD && t!=DI8DEVTYPE_MOUSE){{logline(L"Input enumeration: native controller hidden from game.");return DIENUM_CONTINUE;}}
 return c->callback(d,c->context);
}}''')
  for match in re.finditer(r'STDMETHOD(?:_\((\w+),(\w+)\)|\((\w+)\))\(THIS(_\s+.*?)?\) PURE;',text):
   ret,name=match[1] or 'HRESULT',match[2] or match[3]
   args=(match[4] or '')[1:].strip()
   names=[re.search(r'(\w+)\s*$',a)[1] for a in args.split(',')] if args else []
   body='return raw->'+name+'('+','.join(names)+');'
   if name=='QueryInterface':
    ids=[f'IID_{interface}','IID_IUnknown']
    if device:ids += [f'IID_IDirectInputDevice{v}{suffix}' for v in ['', '2','7']]
    body='if(!ppvObject)return E_POINTER;*ppvObject=nullptr;if('+ '||'.join('riid=='+x for x in ids)+'){*ppvObject=this;AddRef();return S_OK;}return E_NOINTERFACE;'
   elif name=='AddRef':body='return (ULONG)InterlockedIncrement(&refs);'
   elif name=='Release':body='LONG n=InterlockedDecrement(&refs);if(!n)delete this;return (ULONG)n;'
   elif device and name=='SetDataFormat':body='HRESULT hr=raw->SetDataFormat(lpdf);if(SUCCEEDED(hr)){format=standardKeyboardFormat(lpdf);logline(format?L"Keyboard standard format: remapping enabled.":L"Keyboard nonstandard format: pass-through.");}return hr;'
   elif device and name=='GetDeviceState':body='if(hybridMode&&format)return hybrid.getState(raw,cbData,lpvData);HRESULT hr=raw->GetDeviceState(cbData,lpvData);if(SUCCEEDED(hr)&&format&&cbData==256&&lpvData){keymap.state((BYTE*)lpvData);if(!InterlockedExchange(&stateLogged,1))logline(L"Keyboard GetDeviceState remapped successfully.");}return hr;'
   elif device and name=='GetDeviceData':body='if(hybridMode&&format)return hybrid.getData(raw,cbObjectData,rgdod,pdwInOut,dwFlags);HRESULT hr=raw->GetDeviceData(cbObjectData,rgdod,pdwInOut,dwFlags);if(SUCCEEDED(hr)&&format&&rgdod&&pdwInOut){keymap.events(cbObjectData,rgdod,*pdwInOut);if(*pdwInOut&&!InterlockedExchange(&dataLogged,1))logline(L"Keyboard GetDeviceData remapped successfully.");}return hr;'
   elif not device and name=='CreateDevice':body=f'''HRESULT hr=raw->CreateDevice(rguid,lplpDirectInputDevice,pUnkOuter);
if(FAILED(hr)||pUnkOuter||!lplpDirectInputDevice||!*lplpDirectInputDevice)return hr;
DIDEVCAPS caps={{}};caps.dwSize=sizeof(caps);auto d=*lplpDirectInputDevice;
HRESULT capResult=d->GetCapabilities(&caps);
if(SUCCEEDED(capResult)&&GET_DIDEVICE_TYPE(caps.dwDevType)!=DI8DEVTYPE_KEYBOARD&&GET_DIDEVICE_TYPE(caps.dwDevType)!=DI8DEVTYPE_MOUSE){{
 d->Release();*lplpDirectInputDevice=nullptr;logline(L"Input CreateDevice: native controller refused for game.");return DIERR_DEVICENOTREG;
}}
if(SUCCEEDED(capResult)&&GET_DIDEVICE_TYPE(caps.dwDevType)==DI8DEVTYPE_KEYBOARD){{
 auto wrapped=new(std::nothrow)Keyboard{suffix}(d);if(!wrapped){{d->Release();*lplpDirectInputDevice=nullptr;return E_OUTOFMEMORY;}}
 *lplpDirectInputDevice=wrapped;logline(L"Keyboard device wrapped.");
}}return hr;'''
   elif not device and name=='EnumDevices':body='if(!lpCallback)return DIERR_INVALIDPARAM;EnumContext c={lpCallback,pvRef};return raw->EnumDevices(dwDevType,filter,&c,dwFlags);'
   elif not device and name=='EnumDevicesBySemantics':body='logline(L"Input EnumDevicesBySemantics refused in keyboard/hybrid mode.");return DIERR_UNSUPPORTED;'
   out.append(f' {ret} STDMETHODCALLTYPE {name}({args}) noexcept override {{ {body} }}')
  out.append('};')
pathlib.Path(__file__).with_name('wrappers.generated.h').write_text('\n'.join(out))
