// Generated by generate_wrappers.py; forwarding signatures from dinput.h.
class KeyboardA final : public IDirectInputDevice8A {
public:
 IDirectInputDevice8A* raw; LONG refs=1; bool format=false; LONG stateLogged=0,dataLogged=0; HybridKeyboard hybrid;
 explicit KeyboardA(IDirectInputDevice8A* p):raw(p){}
 ~KeyboardA(){raw->Release();}
 HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, void** ppvObject) noexcept override { if(!ppvObject)return E_POINTER;*ppvObject=nullptr;if(riid==IID_IDirectInputDevice8A||riid==IID_IUnknown||riid==IID_IDirectInputDeviceA||riid==IID_IDirectInputDevice2A||riid==IID_IDirectInputDevice7A){*ppvObject=this;AddRef();return S_OK;}return E_NOINTERFACE; }
 ULONG STDMETHODCALLTYPE AddRef() noexcept override { return (ULONG)InterlockedIncrement(&refs); }
 ULONG STDMETHODCALLTYPE Release() noexcept override { LONG n=InterlockedDecrement(&refs);if(!n)delete this;return (ULONG)n; }
 HRESULT STDMETHODCALLTYPE GetCapabilities(LPDIDEVCAPS lpDIDevCaps) noexcept override { return raw->GetCapabilities(lpDIDevCaps); }
 HRESULT STDMETHODCALLTYPE EnumObjects(LPDIENUMDEVICEOBJECTSCALLBACKA lpCallback, LPVOID pvRef, DWORD dwFlags) noexcept override { return raw->EnumObjects(lpCallback,pvRef,dwFlags); }
 HRESULT STDMETHODCALLTYPE GetProperty(REFGUID rguidProp, LPDIPROPHEADER pdiph) noexcept override { return raw->GetProperty(rguidProp,pdiph); }
 HRESULT STDMETHODCALLTYPE SetProperty(REFGUID rguidProp, LPCDIPROPHEADER pdiph) noexcept override { return raw->SetProperty(rguidProp,pdiph); }
 HRESULT STDMETHODCALLTYPE Acquire() noexcept override { return raw->Acquire(); }
 HRESULT STDMETHODCALLTYPE Unacquire() noexcept override { return raw->Unacquire(); }
 HRESULT STDMETHODCALLTYPE GetDeviceState(DWORD cbData, LPVOID lpvData) noexcept override { if(hybridMode&&format)return hybrid.getState(raw,cbData,lpvData);HRESULT hr=raw->GetDeviceState(cbData,lpvData);if(SUCCEEDED(hr)&&format&&cbData==256&&lpvData){keymap.state((BYTE*)lpvData);if(!InterlockedExchange(&stateLogged,1))logline(L"Keyboard GetDeviceState remapped successfully.");}return hr; }
 HRESULT STDMETHODCALLTYPE GetDeviceData(DWORD cbObjectData, LPDIDEVICEOBJECTDATA rgdod, LPDWORD pdwInOut, DWORD dwFlags) noexcept override { if(hybridMode&&format)return hybrid.getData(raw,cbObjectData,rgdod,pdwInOut,dwFlags);HRESULT hr=raw->GetDeviceData(cbObjectData,rgdod,pdwInOut,dwFlags);if(SUCCEEDED(hr)&&format&&rgdod&&pdwInOut){keymap.events(cbObjectData,rgdod,*pdwInOut);if(*pdwInOut&&!InterlockedExchange(&dataLogged,1))logline(L"Keyboard GetDeviceData remapped successfully.");}return hr; }
 HRESULT STDMETHODCALLTYPE SetDataFormat(LPCDIDATAFORMAT lpdf) noexcept override { HRESULT hr=raw->SetDataFormat(lpdf);if(SUCCEEDED(hr)){format=standardKeyboardFormat(lpdf);logline(format?L"Keyboard standard format: remapping enabled.":L"Keyboard nonstandard format: pass-through.");}return hr; }
 HRESULT STDMETHODCALLTYPE SetEventNotification(HANDLE hEvent) noexcept override { return raw->SetEventNotification(hEvent); }
 HRESULT STDMETHODCALLTYPE SetCooperativeLevel(HWND hwnd, DWORD dwFlags) noexcept override { return raw->SetCooperativeLevel(hwnd,dwFlags); }
 HRESULT STDMETHODCALLTYPE GetObjectInfo(LPDIDEVICEOBJECTINSTANCEA pdidoi, DWORD dwObj, DWORD dwHow) noexcept override { return raw->GetObjectInfo(pdidoi,dwObj,dwHow); }
 HRESULT STDMETHODCALLTYPE GetDeviceInfo(LPDIDEVICEINSTANCEA pdidi) noexcept override { return raw->GetDeviceInfo(pdidi); }
 HRESULT STDMETHODCALLTYPE RunControlPanel(HWND hwndOwner, DWORD dwFlags) noexcept override { return raw->RunControlPanel(hwndOwner,dwFlags); }
 HRESULT STDMETHODCALLTYPE Initialize(HINSTANCE hinst, DWORD dwVersion, REFGUID rguid) noexcept override { return raw->Initialize(hinst,dwVersion,rguid); }
 HRESULT STDMETHODCALLTYPE CreateEffect(REFGUID rguid, LPCDIEFFECT lpeff, LPDIRECTINPUTEFFECT *ppdeff, LPUNKNOWN punkOuter) noexcept override { return raw->CreateEffect(rguid,lpeff,ppdeff,punkOuter); }
 HRESULT STDMETHODCALLTYPE EnumEffects(LPDIENUMEFFECTSCALLBACKA lpCallback, LPVOID pvRef, DWORD dwEffType) noexcept override { return raw->EnumEffects(lpCallback,pvRef,dwEffType); }
 HRESULT STDMETHODCALLTYPE GetEffectInfo(LPDIEFFECTINFOA pdei, REFGUID rguid) noexcept override { return raw->GetEffectInfo(pdei,rguid); }
 HRESULT STDMETHODCALLTYPE GetForceFeedbackState(LPDWORD pdwOut) noexcept override { return raw->GetForceFeedbackState(pdwOut); }
 HRESULT STDMETHODCALLTYPE SendForceFeedbackCommand(DWORD dwFlags) noexcept override { return raw->SendForceFeedbackCommand(dwFlags); }
 HRESULT STDMETHODCALLTYPE EnumCreatedEffectObjects(LPDIENUMCREATEDEFFECTOBJECTSCALLBACK lpCallback, LPVOID pvRef, DWORD fl) noexcept override { return raw->EnumCreatedEffectObjects(lpCallback,pvRef,fl); }
 HRESULT STDMETHODCALLTYPE Escape(LPDIEFFESCAPE pesc) noexcept override { return raw->Escape(pesc); }
 HRESULT STDMETHODCALLTYPE Poll() noexcept override { return raw->Poll(); }
 HRESULT STDMETHODCALLTYPE SendDeviceData(DWORD cbObjectData, LPCDIDEVICEOBJECTDATA rgdod, LPDWORD pdwInOut, DWORD fl) noexcept override { return raw->SendDeviceData(cbObjectData,rgdod,pdwInOut,fl); }
 HRESULT STDMETHODCALLTYPE EnumEffectsInFile(LPCSTR lpszFileName,LPDIENUMEFFECTSINFILECALLBACK pec,LPVOID pvRef,DWORD dwFlags) noexcept override { return raw->EnumEffectsInFile(lpszFileName,pec,pvRef,dwFlags); }
 HRESULT STDMETHODCALLTYPE WriteEffectToFile(LPCSTR lpszFileName,DWORD dwEntries,LPDIFILEEFFECT rgDiFileEft,DWORD dwFlags) noexcept override { return raw->WriteEffectToFile(lpszFileName,dwEntries,rgDiFileEft,dwFlags); }
 HRESULT STDMETHODCALLTYPE BuildActionMap(LPDIACTIONFORMATA lpdiaf, LPCSTR lpszUserName, DWORD dwFlags) noexcept override { return raw->BuildActionMap(lpdiaf,lpszUserName,dwFlags); }
 HRESULT STDMETHODCALLTYPE SetActionMap(LPDIACTIONFORMATA lpdiaf, LPCSTR lpszUserName, DWORD dwFlags) noexcept override { return raw->SetActionMap(lpdiaf,lpszUserName,dwFlags); }
 HRESULT STDMETHODCALLTYPE GetImageInfo(LPDIDEVICEIMAGEINFOHEADERA lpdiDevImageInfoHeader) noexcept override { return raw->GetImageInfo(lpdiDevImageInfoHeader); }
};
class InputA final : public IDirectInput8A {
public:
 IDirectInput8A* raw; LONG refs=1; bool format=false; LONG stateLogged=0,dataLogged=0; HybridKeyboard hybrid;
 explicit InputA(IDirectInput8A* p):raw(p){}
 ~InputA(){raw->Release();}
struct EnumContext { LPDIENUMDEVICESCALLBACKA callback; void* context; };
static BOOL CALLBACK filter(const DIDEVICEINSTANCEA* d, void* p) {
 auto c=(EnumContext*)p;DWORD t=GET_DIDEVICE_TYPE(d->dwDevType);
 if(t!=DI8DEVTYPE_KEYBOARD && t!=DI8DEVTYPE_MOUSE){logline(L"Input enumeration: native controller hidden from game.");return DIENUM_CONTINUE;}
 return c->callback(d,c->context);
}
 HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, void** ppvObject) noexcept override { if(!ppvObject)return E_POINTER;*ppvObject=nullptr;if(riid==IID_IDirectInput8A||riid==IID_IUnknown){*ppvObject=this;AddRef();return S_OK;}return E_NOINTERFACE; }
 ULONG STDMETHODCALLTYPE AddRef() noexcept override { return (ULONG)InterlockedIncrement(&refs); }
 ULONG STDMETHODCALLTYPE Release() noexcept override { LONG n=InterlockedDecrement(&refs);if(!n)delete this;return (ULONG)n; }
 HRESULT STDMETHODCALLTYPE CreateDevice(REFGUID rguid, LPDIRECTINPUTDEVICE8A *lplpDirectInputDevice, LPUNKNOWN pUnkOuter) noexcept override { HRESULT hr=raw->CreateDevice(rguid,lplpDirectInputDevice,pUnkOuter);
if(FAILED(hr)||pUnkOuter||!lplpDirectInputDevice||!*lplpDirectInputDevice)return hr;
DIDEVCAPS caps={};caps.dwSize=sizeof(caps);auto d=*lplpDirectInputDevice;
HRESULT capResult=d->GetCapabilities(&caps);
if(SUCCEEDED(capResult)&&GET_DIDEVICE_TYPE(caps.dwDevType)!=DI8DEVTYPE_KEYBOARD&&GET_DIDEVICE_TYPE(caps.dwDevType)!=DI8DEVTYPE_MOUSE){
 d->Release();*lplpDirectInputDevice=nullptr;logline(L"Input CreateDevice: native controller refused for game.");return DIERR_DEVICENOTREG;
}
if(SUCCEEDED(capResult)&&GET_DIDEVICE_TYPE(caps.dwDevType)==DI8DEVTYPE_KEYBOARD){
 auto wrapped=new(std::nothrow)KeyboardA(d);if(!wrapped){d->Release();*lplpDirectInputDevice=nullptr;return E_OUTOFMEMORY;}
 *lplpDirectInputDevice=wrapped;logline(L"Keyboard device wrapped.");
}return hr; }
 HRESULT STDMETHODCALLTYPE EnumDevices(DWORD dwDevType, LPDIENUMDEVICESCALLBACKA lpCallback, LPVOID pvRef, DWORD dwFlags) noexcept override { if(!lpCallback)return DIERR_INVALIDPARAM;EnumContext c={lpCallback,pvRef};return raw->EnumDevices(dwDevType,filter,&c,dwFlags); }
 HRESULT STDMETHODCALLTYPE GetDeviceStatus(REFGUID rguidInstance) noexcept override { return raw->GetDeviceStatus(rguidInstance); }
 HRESULT STDMETHODCALLTYPE RunControlPanel(HWND hwndOwner, DWORD dwFlags) noexcept override { return raw->RunControlPanel(hwndOwner,dwFlags); }
 HRESULT STDMETHODCALLTYPE Initialize(HINSTANCE hinst, DWORD dwVersion) noexcept override { return raw->Initialize(hinst,dwVersion); }
 HRESULT STDMETHODCALLTYPE FindDevice(REFGUID rguid, LPCSTR pszName, LPGUID pguidInstance) noexcept override { return raw->FindDevice(rguid,pszName,pguidInstance); }
 HRESULT STDMETHODCALLTYPE EnumDevicesBySemantics(LPCSTR ptszUserName, LPDIACTIONFORMATA lpdiActionFormat, LPDIENUMDEVICESBYSEMANTICSCBA lpCallback, LPVOID pvRef, DWORD dwFlags) noexcept override { logline(L"Input EnumDevicesBySemantics refused in keyboard/hybrid mode.");return DIERR_UNSUPPORTED; }
 HRESULT STDMETHODCALLTYPE ConfigureDevices(LPDICONFIGUREDEVICESCALLBACK lpdiCallback, LPDICONFIGUREDEVICESPARAMSA lpdiCDParams, DWORD dwFlags, LPVOID pvRefData) noexcept override { return raw->ConfigureDevices(lpdiCallback,lpdiCDParams,dwFlags,pvRefData); }
};
class KeyboardW final : public IDirectInputDevice8W {
public:
 IDirectInputDevice8W* raw; LONG refs=1; bool format=false; LONG stateLogged=0,dataLogged=0; HybridKeyboard hybrid;
 explicit KeyboardW(IDirectInputDevice8W* p):raw(p){}
 ~KeyboardW(){raw->Release();}
 HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, void** ppvObject) noexcept override { if(!ppvObject)return E_POINTER;*ppvObject=nullptr;if(riid==IID_IDirectInputDevice8W||riid==IID_IUnknown||riid==IID_IDirectInputDeviceW||riid==IID_IDirectInputDevice2W||riid==IID_IDirectInputDevice7W){*ppvObject=this;AddRef();return S_OK;}return E_NOINTERFACE; }
 ULONG STDMETHODCALLTYPE AddRef() noexcept override { return (ULONG)InterlockedIncrement(&refs); }
 ULONG STDMETHODCALLTYPE Release() noexcept override { LONG n=InterlockedDecrement(&refs);if(!n)delete this;return (ULONG)n; }
 HRESULT STDMETHODCALLTYPE GetCapabilities(LPDIDEVCAPS lpDIDevCaps) noexcept override { return raw->GetCapabilities(lpDIDevCaps); }
 HRESULT STDMETHODCALLTYPE EnumObjects(LPDIENUMDEVICEOBJECTSCALLBACKW lpCallback, LPVOID pvRef, DWORD dwFlags) noexcept override { return raw->EnumObjects(lpCallback,pvRef,dwFlags); }
 HRESULT STDMETHODCALLTYPE GetProperty(REFGUID rguidProp, LPDIPROPHEADER pdiph) noexcept override { return raw->GetProperty(rguidProp,pdiph); }
 HRESULT STDMETHODCALLTYPE SetProperty(REFGUID rguidProp, LPCDIPROPHEADER pdiph) noexcept override { return raw->SetProperty(rguidProp,pdiph); }
 HRESULT STDMETHODCALLTYPE Acquire() noexcept override { return raw->Acquire(); }
 HRESULT STDMETHODCALLTYPE Unacquire() noexcept override { return raw->Unacquire(); }
 HRESULT STDMETHODCALLTYPE GetDeviceState(DWORD cbData, LPVOID lpvData) noexcept override { if(hybridMode&&format)return hybrid.getState(raw,cbData,lpvData);HRESULT hr=raw->GetDeviceState(cbData,lpvData);if(SUCCEEDED(hr)&&format&&cbData==256&&lpvData){keymap.state((BYTE*)lpvData);if(!InterlockedExchange(&stateLogged,1))logline(L"Keyboard GetDeviceState remapped successfully.");}return hr; }
 HRESULT STDMETHODCALLTYPE GetDeviceData(DWORD cbObjectData, LPDIDEVICEOBJECTDATA rgdod, LPDWORD pdwInOut, DWORD dwFlags) noexcept override { if(hybridMode&&format)return hybrid.getData(raw,cbObjectData,rgdod,pdwInOut,dwFlags);HRESULT hr=raw->GetDeviceData(cbObjectData,rgdod,pdwInOut,dwFlags);if(SUCCEEDED(hr)&&format&&rgdod&&pdwInOut){keymap.events(cbObjectData,rgdod,*pdwInOut);if(*pdwInOut&&!InterlockedExchange(&dataLogged,1))logline(L"Keyboard GetDeviceData remapped successfully.");}return hr; }
 HRESULT STDMETHODCALLTYPE SetDataFormat(LPCDIDATAFORMAT lpdf) noexcept override { HRESULT hr=raw->SetDataFormat(lpdf);if(SUCCEEDED(hr)){format=standardKeyboardFormat(lpdf);logline(format?L"Keyboard standard format: remapping enabled.":L"Keyboard nonstandard format: pass-through.");}return hr; }
 HRESULT STDMETHODCALLTYPE SetEventNotification(HANDLE hEvent) noexcept override { return raw->SetEventNotification(hEvent); }
 HRESULT STDMETHODCALLTYPE SetCooperativeLevel(HWND hwnd, DWORD dwFlags) noexcept override { return raw->SetCooperativeLevel(hwnd,dwFlags); }
 HRESULT STDMETHODCALLTYPE GetObjectInfo(LPDIDEVICEOBJECTINSTANCEW pdidoi, DWORD dwObj, DWORD dwHow) noexcept override { return raw->GetObjectInfo(pdidoi,dwObj,dwHow); }
 HRESULT STDMETHODCALLTYPE GetDeviceInfo(LPDIDEVICEINSTANCEW pdidi) noexcept override { return raw->GetDeviceInfo(pdidi); }
 HRESULT STDMETHODCALLTYPE RunControlPanel(HWND hwndOwner, DWORD dwFlags) noexcept override { return raw->RunControlPanel(hwndOwner,dwFlags); }
 HRESULT STDMETHODCALLTYPE Initialize(HINSTANCE hinst, DWORD dwVersion, REFGUID rguid) noexcept override { return raw->Initialize(hinst,dwVersion,rguid); }
 HRESULT STDMETHODCALLTYPE CreateEffect(REFGUID rguid, LPCDIEFFECT lpeff, LPDIRECTINPUTEFFECT *ppdeff, LPUNKNOWN punkOuter) noexcept override { return raw->CreateEffect(rguid,lpeff,ppdeff,punkOuter); }
 HRESULT STDMETHODCALLTYPE EnumEffects(LPDIENUMEFFECTSCALLBACKW lpCallback, LPVOID pvRef, DWORD dwEffType) noexcept override { return raw->EnumEffects(lpCallback,pvRef,dwEffType); }
 HRESULT STDMETHODCALLTYPE GetEffectInfo(LPDIEFFECTINFOW pdei, REFGUID rguid) noexcept override { return raw->GetEffectInfo(pdei,rguid); }
 HRESULT STDMETHODCALLTYPE GetForceFeedbackState(LPDWORD pdwOut) noexcept override { return raw->GetForceFeedbackState(pdwOut); }
 HRESULT STDMETHODCALLTYPE SendForceFeedbackCommand(DWORD dwFlags) noexcept override { return raw->SendForceFeedbackCommand(dwFlags); }
 HRESULT STDMETHODCALLTYPE EnumCreatedEffectObjects(LPDIENUMCREATEDEFFECTOBJECTSCALLBACK lpCallback, LPVOID pvRef, DWORD fl) noexcept override { return raw->EnumCreatedEffectObjects(lpCallback,pvRef,fl); }
 HRESULT STDMETHODCALLTYPE Escape(LPDIEFFESCAPE pesc) noexcept override { return raw->Escape(pesc); }
 HRESULT STDMETHODCALLTYPE Poll() noexcept override { return raw->Poll(); }
 HRESULT STDMETHODCALLTYPE SendDeviceData(DWORD cbObjectData, LPCDIDEVICEOBJECTDATA rgdod, LPDWORD pdwInOut, DWORD fl) noexcept override { return raw->SendDeviceData(cbObjectData,rgdod,pdwInOut,fl); }
 HRESULT STDMETHODCALLTYPE EnumEffectsInFile(LPCWSTR lpszFileName,LPDIENUMEFFECTSINFILECALLBACK pec,LPVOID pvRef,DWORD dwFlags) noexcept override { return raw->EnumEffectsInFile(lpszFileName,pec,pvRef,dwFlags); }
 HRESULT STDMETHODCALLTYPE WriteEffectToFile(LPCWSTR lpszFileName,DWORD dwEntries,LPDIFILEEFFECT rgDiFileEft,DWORD dwFlags) noexcept override { return raw->WriteEffectToFile(lpszFileName,dwEntries,rgDiFileEft,dwFlags); }
 HRESULT STDMETHODCALLTYPE BuildActionMap(LPDIACTIONFORMATW lpdiaf, LPCWSTR lpszUserName, DWORD dwFlags) noexcept override { return raw->BuildActionMap(lpdiaf,lpszUserName,dwFlags); }
 HRESULT STDMETHODCALLTYPE SetActionMap(LPDIACTIONFORMATW lpdiaf, LPCWSTR lpszUserName, DWORD dwFlags) noexcept override { return raw->SetActionMap(lpdiaf,lpszUserName,dwFlags); }
 HRESULT STDMETHODCALLTYPE GetImageInfo(LPDIDEVICEIMAGEINFOHEADERW lpdiDevImageInfoHeader) noexcept override { return raw->GetImageInfo(lpdiDevImageInfoHeader); }
};
class InputW final : public IDirectInput8W {
public:
 IDirectInput8W* raw; LONG refs=1; bool format=false; LONG stateLogged=0,dataLogged=0; HybridKeyboard hybrid;
 explicit InputW(IDirectInput8W* p):raw(p){}
 ~InputW(){raw->Release();}
struct EnumContext { LPDIENUMDEVICESCALLBACKW callback; void* context; };
static BOOL CALLBACK filter(const DIDEVICEINSTANCEW* d, void* p) {
 auto c=(EnumContext*)p;DWORD t=GET_DIDEVICE_TYPE(d->dwDevType);
 if(t!=DI8DEVTYPE_KEYBOARD && t!=DI8DEVTYPE_MOUSE){logline(L"Input enumeration: native controller hidden from game.");return DIENUM_CONTINUE;}
 return c->callback(d,c->context);
}
 HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, void** ppvObject) noexcept override { if(!ppvObject)return E_POINTER;*ppvObject=nullptr;if(riid==IID_IDirectInput8W||riid==IID_IUnknown){*ppvObject=this;AddRef();return S_OK;}return E_NOINTERFACE; }
 ULONG STDMETHODCALLTYPE AddRef() noexcept override { return (ULONG)InterlockedIncrement(&refs); }
 ULONG STDMETHODCALLTYPE Release() noexcept override { LONG n=InterlockedDecrement(&refs);if(!n)delete this;return (ULONG)n; }
 HRESULT STDMETHODCALLTYPE CreateDevice(REFGUID rguid, LPDIRECTINPUTDEVICE8W *lplpDirectInputDevice, LPUNKNOWN pUnkOuter) noexcept override { HRESULT hr=raw->CreateDevice(rguid,lplpDirectInputDevice,pUnkOuter);
if(FAILED(hr)||pUnkOuter||!lplpDirectInputDevice||!*lplpDirectInputDevice)return hr;
DIDEVCAPS caps={};caps.dwSize=sizeof(caps);auto d=*lplpDirectInputDevice;
HRESULT capResult=d->GetCapabilities(&caps);
if(SUCCEEDED(capResult)&&GET_DIDEVICE_TYPE(caps.dwDevType)!=DI8DEVTYPE_KEYBOARD&&GET_DIDEVICE_TYPE(caps.dwDevType)!=DI8DEVTYPE_MOUSE){
 d->Release();*lplpDirectInputDevice=nullptr;logline(L"Input CreateDevice: native controller refused for game.");return DIERR_DEVICENOTREG;
}
if(SUCCEEDED(capResult)&&GET_DIDEVICE_TYPE(caps.dwDevType)==DI8DEVTYPE_KEYBOARD){
 auto wrapped=new(std::nothrow)KeyboardW(d);if(!wrapped){d->Release();*lplpDirectInputDevice=nullptr;return E_OUTOFMEMORY;}
 *lplpDirectInputDevice=wrapped;logline(L"Keyboard device wrapped.");
}return hr; }
 HRESULT STDMETHODCALLTYPE EnumDevices(DWORD dwDevType, LPDIENUMDEVICESCALLBACKW lpCallback, LPVOID pvRef, DWORD dwFlags) noexcept override { if(!lpCallback)return DIERR_INVALIDPARAM;EnumContext c={lpCallback,pvRef};return raw->EnumDevices(dwDevType,filter,&c,dwFlags); }
 HRESULT STDMETHODCALLTYPE GetDeviceStatus(REFGUID rguidInstance) noexcept override { return raw->GetDeviceStatus(rguidInstance); }
 HRESULT STDMETHODCALLTYPE RunControlPanel(HWND hwndOwner, DWORD dwFlags) noexcept override { return raw->RunControlPanel(hwndOwner,dwFlags); }
 HRESULT STDMETHODCALLTYPE Initialize(HINSTANCE hinst, DWORD dwVersion) noexcept override { return raw->Initialize(hinst,dwVersion); }
 HRESULT STDMETHODCALLTYPE FindDevice(REFGUID rguid, LPCWSTR pszName, LPGUID pguidInstance) noexcept override { return raw->FindDevice(rguid,pszName,pguidInstance); }
 HRESULT STDMETHODCALLTYPE EnumDevicesBySemantics(LPCWSTR ptszUserName, LPDIACTIONFORMATW lpdiActionFormat, LPDIENUMDEVICESBYSEMANTICSCBW lpCallback, LPVOID pvRef, DWORD dwFlags) noexcept override { logline(L"Input EnumDevicesBySemantics refused in keyboard/hybrid mode.");return DIERR_UNSUPPORTED; }
 HRESULT STDMETHODCALLTYPE ConfigureDevices(LPDICONFIGUREDEVICESCALLBACK lpdiCallback, LPDICONFIGUREDEVICESPARAMSW lpdiCDParams, DWORD dwFlags, LPVOID pvRefData) noexcept override { return raw->ConfigureDevices(lpdiCallback,lpdiCDParams,dwFlags,pvRefData); }
};